namespace: community
name: amazon
version: 0.1.0
readme: README.md
authors: null
description: null
license: GPL-3.0-or-later
license_file: COPYING
tags: null
dependencies:
  ansible.amazon: '>=0.1.0'
repository: git@github.com:coll-test/community.amazon.git
documentation: https://github.com/coll-test/community.amazon/tree/master/docs
homepage: https://github.com/coll-test/community.amazon
issues: https://github.com/coll-test/community.amazon/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
